# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'baiDeBuDeQiJie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
  # Pods for baiDeBuDeQiJie

end
